title: ThRoot - Cybersecurity Journey 🚀
description: Portfólio técnico, estudos e publicações sobre segurança da informação por Thiago Amaral.
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
aux_links:
  GitHub: https://github.com/0xThiagoAmaral/lab.throot.com.br
plugins:
  - jekyll-remote-theme
