title: "ThRoot - HomeLab & Cybersecurity Journey 🚀"
description: "Portfólio Técnico de Segurança da Informação - por Thiago Amaral"
theme: "just-the-docs"
url: "https://lab.throot.com.br"
aux_links:
  GitHub: https://github.com/0xThiagoAmaral
