title: "ThRoot - HomeLab & Cybersecurity Journey 🚀"
description: "Portfólio técnico, estudos e publicações sobre Segurança da Informação por Thiago Amaral"
theme: "just-the-docs"
url: "https://lab.throot.com.br"

aux_links:
  GitHub: https://github.com/0xThiagoAmaral
